project:
  type: website
  output-dir: docs # Crucial: tells Quarto where to put the files

website:
  title: "Набори високої цінності"
  navbar:
    left:
        file: index.qmd # Or whatever your main file is named

format:
  html:
    theme: cosmo