project:
  type: website
  output-dir: docs

website:
  title: ""          # Metadata title (keeps browser tab clean)
  navbar:
    title: false     # Removes "My Quarto Site" from the visual header
    left: []         # explicitly empty list removes "Home"

format:
  html:
    theme: cosmo